source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'rails-api'
gem 'pg'
gem 'bcrypt', '~> 3.1.7'
gem 'has_secure_token'
gem 'active_model_serializers'

group :test do
  gem 'shoulda-matchers'
end

group :development, :test do
  gem 'pry-rails'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'spring'
  gem 'rspec-rails'
  gem 'bullet'
  gem 'simplecov'
end
